id: CVE-2026-25326-cmsmasters_content_composer-00d8e7db-b1a4-4785-ba57-1dce0fd11dec

info:
  name: >
    CMSMasters Content Composer <= 1.4.5 - Authenticated (Contributor+) Local File Inclusion
  author: topscoder
  severity: low
  description: >
    The CMSMasters Content Composer plugin for WordPress is vulnerable to Local File Inclusion in versions up to, and including, 1.4.5. This makes it possible for authenticated attackers, with contributor-level access and above, to include and execute arbitrary files on the server, allowing the execution of any PHP code in those files. This can be used to bypass access controls, obtain sensitive data, or achieve code execution in cases where images and other "safe" file types can be uploaded and included.
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/00d8e7db-b1a4-4785-ba57-1dce0fd11dec?source=api-prod
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:H/I:H/A:H
    cvss-score: 7.5
    cve-id: CVE-2026-25326
  metadata:
    fofa-query: "wp-content/plugins/cmsmasters-content-composer/"
    google-query: inurl:"/wp-content/plugins/cmsmasters-content-composer/"
    shodan-query: 'http.html:"wp-content/plugins/cmsmasters-content-composer/"'
  tags: cve,wordpress,wp-plugin,cmsmasters-content-composer,low,production

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/cmsmasters-content-composer/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag:\\s*([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "cmsmasters-content-composer"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 1.4.5')